require 'rubygems'

require 'bundler'
Bundler.require

require 'rake/testtask'

require File.join(File.dirname(__FILE__), "lib", "health")

desc "Cache the Repo"
task :cache_repo, [:repo] do |t, args|
  repo = args[:repo]

  # TODO: Abort if no repo

  puts "Caching Repo: #{repo}"

  Health.new.cache_health_reading_from_repo(repo)
end

desc "Migrate HealthReading"
task :migrate_health_reading do
  HealthReading.run_migration_up
end

desc "Drop HealthReading"
task :drop_health_reading do
  HealthReading.drop_table
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*test.rb']
  t.verbose = true
end

desc "Seed Repos"
task :seed_repos do
  repos = File.readlines(File.join(File.dirname(__FILE__), "data", "seed_repos.txt"))

  puts "Seeding #{repos.count} repos"

  repos.reverse.each do |repo|
    repo.strip!
    begin
      puts "Seed #{repo}"
      Health.new.cache_health_reading_from_repo(repo)
    rescue
      puts "Error #{$!}"
    end
  end
end
