require 'rubygems'

require 'bundler'
Bundler.require

require File.join(File.dirname(__FILE__), "lib", "health")

desc "Cache the Repo"
task :cache_repo, [:repo] do |t, args|
  repo = args[:repo]

  # TODO: Abort if no repo

  puts "Caching Repo: #{repo}"

  Health.cache_health_reading_from_repo(repo)
end

desc "Migrate HealthReading"
task :migrate_health_reading do
  HealthReading.run_migration_up
end
