require 'rubygems'

require 'bundler'
Bundler.require



desc "Cache the Repo"
task :cache_repo, [:repo] do |t, args|
  require File.join(File.dirname(__FILE__), "lib", "health")
  
  repo = args[:repo]

  # TODO: Abort if no repo

  puts "Caching Repo: #{repo}"

  Health.cache_health_reading_from_repo(repo)
end
